extends "res://tests/expedition_test.gd"

func select_pipo() -> void:
	await frames(25)
	if level.tico!=level.pipo: level.switch_character()
	await frames(20)

func select_tico() -> void:
	await frames(25)
	if level.tico!=level.squirrel: level.switch_character()
	await frames(20)

func charge_at(x: float) -> void:
	await select_pipo()
	await walk_to(x)
	await frames(20)
	key(KEY_E,true)
	await frames(65)
	key(KEY_E,false)

func finish_at(x: float) -> void:
	await walk_to(x)
	await frames(60)
	check(level.completed,"Percurso completo: "+level.NAMES[level.biome][level.section])
	var snapshot: Dictionary = level.world_snapshot()
	check(snapshot.rescued and snapshot.completed,"Snapshot conserva dupla e conclusão")
	await close_level()

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	await open_stage(2,"2")
	await select_pipo()
	await walk_to(800)
	check(level.mechanisms.Tronco.active,"2-2: Pipo derruba tronco e cria passagem")
	await walk_to(2090)
	await select_tico()
	await glide_to(2710)
	await glide_to(3350)
	await finish_at(3590)

	await open_stage(2,"3")
	await walk_to(610)
	await glide_to(1250)
	await charge_at(1290)
	check(level.mechanisms.Ponte.active,"2-3: investida baixa a grande ponte")
	await select_tico()
	await walk_to(2400)
	await glide_to(2690)
	await glide_to(3310)
	await finish_at(3590)

	await open_stage(3,"2")
	await walk_to(1330)
	check(level.tico.position.x>1230,"3-2: Tico atravessa caverna estreita")
	await charge_at(1320)
	check(level.mechanisms.Rocha.active,"3-2: Pipo abre a passagem rochosa")
	await walk_to(1610)
	await frames(30)
	check(level.secret.revealed,"3-2: faro revela segredo na caverna")
	await select_tico()
	await glide_to(2410)
	await glide_to(3060)
	await glide_to(3440)
	await finish_at(3600)

	await open_stage(3,"3")
	await glide_to(1100)
	await glide_to(1770)
	await glide_to(2600)
	await glide_to(3340)
	await finish_at(3600)

	await open_stage(4,"2")
	await charge_at(650)
	check(level.mechanisms.Comporta.active and level.water.is_empty(),"4-2: comporta reduz nível da água")
	await select_tico()
	await walk_to(2200)
	check(level.checkpoint_active,"4-2: Tico atravessa a passagem revelada pela água")
	await glide_to(2810)
	await finish_at(3600)

	await open_stage(4,"3")
	await select_pipo()
	await walk_to(800)
	check(level.mechanisms.Tora.active,"4-3: tora cria primeiro caminho")
	await walk_to(1830)
	await frames(45)
	check(level.mechanisms.Roda.active,"4-3: peso liga roda e elevador")
	await walk_to(2110)
	await select_tico()
	await glide_to(2720)
	await glide_to(3020)
	await charge_at(3060)
	check(level.mechanisms.Engrenagem.active,"4-3: investida destrava última engrenagem")
	await finish_at(3640)
	print("RESULTADO: %d verificações, %d falhas" % [checks,failures])
	quit(1 if failures else 0)
