extends "res://tests/expedition_test.gd"

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	await open_stage(2,"1")
	if level.tico!=level.pipo: level.switch_character()
	await frames(12)
	var cargo: Node2D = level.mechanisms.CargaRio
	await place(cargo.position,4)
	key(KEY_E,true)
	await frames(2)
	key(KEY_E,false)
	check(cargo.carried and level.pipo.ability=="ready","AÇÃO recolhe o cesto em vez de iniciar a investida")
	await frames(3)
	check(level.pipo.is_carrying() and not level.switch_character(),"Transporte mantém Pipo ativo até soltar ou entregar")
	check(cargo.pickup_progress>0.0 and cargo.pickup_progress<1.0 and cargo.position.y<cargo.pickup_from.y,"Cesta sobe progressivamente das mãos até acima da cabeça")
	await frames(24)
	check(cargo.pickup_progress==1.0 and cargo.position.y<level.pipo.position.y-100,"Pipo sustenta a cesta acima da cabeça")
	await frames(2)
	check(level.pipo.move_speed==level.pipo.CARRY_MOVE_SPEED and level.pipo.jump_velocity==0,"Carga reduz a velocidade e impede o salto")
	level.drop_carried_object()
	check(not cargo.carried and not level.pipo.is_carrying(),"Pipo pode soltar o cesto em local seguro")
	await place(cargo.position,4)
	check(level.try_pipo_carry(level.pipo),"Cesto solto pode ser recolhido novamente")
	await place(cargo.destination,4)
	check(cargo.delivery_hint.visible and cargo.delivery_hint.text.contains("ENTREGA"),"Área de depósito sinaliza claramente a entrega")
	check(level.try_pipo_carry(level.pipo) and cargo.active,"AÇÃO na marca entrega as provisões")
	check(level.mechanisms.CargaRio.active,"Entrega integra o mecanismo necessário da fase")
	await close_level()
	await open_stage(2,"2")
	check(level.mechanisms.has("CargaMargem"),"2-2 possui transporte de provisões")
	await close_level()
	await open_stage(2,"3")
	check(level.mechanisms.has("CargaPonte"),"2-3 possui transporte de provisões")
	await close_level()
	print("RESULTADO TRANSPORTE DE OBJETOS: %d verificações, %d falhas" % [checks,failures])
	quit(1 if failures else 0)
