extends "res://tests/expedition_test.gd"

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	await open_stage(2,"1")
	if level.tico!=level.pipo: level.switch_character()
	await frames(12)
	var cargo: Node2D = level.mechanisms.CargaRio
	check(cargo.BASKET.resource_path.ends_with("food_basket.png") and cargo.DONKEY_CART.resource_path.ends_with("donkey_cart.png"),"Cesta e carroça usam os novos assets ilustrados")
	await place(cargo.position,4)
	key(KEY_E,true)
	await frames(2)
	key(KEY_E,false)
	check(cargo.carried and level.pipo.ability=="ready","AÇÃO recolhe o cesto em vez de iniciar a investida")
	await frames(3)
	check(level.pipo.is_carrying() and not level.switch_character(),"Transporte mantém Pipo ativo até soltar ou entregar")
	check(cargo.pickup_progress>0.0 and cargo.pickup_progress<1.0 and cargo.position.y<cargo.pickup_from.y,"Cesta sobe progressivamente das mãos até acima da cabeça")
	await frames(24)
	check(cargo.pickup_progress==1.0 and cargo.position.y<level.pipo.position.y-100,"Pipo sustenta a cesta acima da cabeça")
	var art: Node2D = level.pipo.get_node("Illustration")
	check(art._carry_frames.size()==4 and art.pose=="carry","Pipo usa ciclo próprio de quatro poses para transportar a cesta")
	await frames(2)
	check(is_equal_approx(level.pipo.move_speed,level.pipo.CARRY_MOVE_SPEED*level.RIVER_PIPO_SPEED_SCALE) and level.pipo.jump_velocity==0,"Carga reduz a velocidade e impede o salto")
	level.drop_carried_object()
	check(not cargo.carried and not level.pipo.is_carrying(),"Pipo pode soltar o cesto em local seguro")
	await place(cargo.position,4)
	check(level.try_pipo_carry(level.pipo),"Cesto solto pode ser recolhido novamente")
	await place(cargo.destination,4)
	check(cargo.delivery_hint.visible and cargo.delivery_hint.text.contains("ENTREGA"),"Área de depósito sinaliza claramente a entrega")
	level._apply_device("TroncoRio",false)
	level._apply_device("PesoCorrente",false)
	level._on_exit(level.exit_marker)
	check(not level.completed and not level.exit_marker.activated,"Portal permanece bloqueado enquanto a carroça espera a cesta")
	check(level.try_pipo_carry(level.pipo) and cargo.active,"AÇÃO na marca entrega as provisões")
	check(level.mechanisms.CargaRio.active,"Entrega integra o mecanismo necessário da fase")
	level._on_exit(level.exit_marker)
	check(level.completed,"Portal permite concluir a fase depois da entrega na carroça")
	await close_level()
	await open_stage(2,"2")
	check(level.mechanisms.has("CargaMargem"),"2-2 possui transporte de provisões")
	await close_level()
	await open_stage(2,"3")
	check(level.mechanisms.has("CargaPonte"),"2-3 possui transporte de provisões")
	await close_level()
	print("RESULTADO TRANSPORTE DE OBJETOS: %d verificações, %d falhas" % [checks,failures])
	quit(1 if failures else 0)
