extends "res://tests/expedition_test.gd"

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	await open_stage(2,"1")
	if level.tico!=level.pipo: level.switch_character()
	await frames(12)
	var cargo: Node2D = level.mechanisms.CargaRio
	check(cargo.BASKET.resource_path.ends_with("food_basket.png") and cargo.DONKEY_CART.resource_path.ends_with("donkey_cart.png"),"Cesta e carroça usam os novos assets ilustrados")
	check(cargo.required_mechanism==&"" and cargo._passage_is_open(),"Cesta fica acessível diretamente para a sequência de transporte")
	await place(cargo.position,4)
	key(KEY_E,true)
	await frames(2)
	key(KEY_E,false)
	check(cargo.carried and level.pipo.ability=="ready","AÇÃO recolhe o cesto em vez de iniciar a investida")
	await frames(3)
	check(level.pipo.is_carrying() and not level.switch_character(),"Transporte mantém Pipo ativo até soltar ou entregar")
	check(cargo.pickup_progress>0.0 and cargo.pickup_progress<1.0 and cargo.position.y<cargo.pickup_from.y,"Cesta sobe progressivamente das mãos até acima da cabeça")
	await frames(24)
	check(cargo.pickup_progress==1.0 and cargo.position.y<level.pipo.position.y-100,"Pipo sustenta a cesta acima da cabeça")
	var art: Node2D = level.pipo.get_node("Illustration")
	check(art._carry_frames.size()==4 and art.pose=="carry","Pipo usa ciclo próprio de quatro poses para transportar a cesta")
	var carry_region: Rect2 = art._carry_frames[0].region
	check(carry_region.position.y==120.0 and carry_region.end.y==785.0 and art.PIPO_CARRY_HEIGHT==119.0,"Recorte remove a margem transparente e mantém os pés de Pipo junto ao chão")
	await frames(2)
	check(is_equal_approx(level.pipo.move_speed,level.pipo.CARRY_MOVE_SPEED*level.RIVER_PIPO_SPEED_SCALE) and level.pipo.jump_velocity==0,"Carga reduz a velocidade e impede o salto")
	level.drop_carried_object()
	check(not cargo.carried and not level.pipo.is_carrying(),"Pipo pode soltar o cesto em local seguro")
	await place(cargo.position,4)
	check(level.try_pipo_carry(level.pipo),"Cesto solto pode ser recolhido novamente")
	await place(cargo.destination+Vector2(-230,0),4)
	check(cargo.delivery_hint.visible and cargo.delivery_hint.text.contains("APROXIME-SE"),"Área da carroça sinaliza que basta se aproximar para entregar")
	level._apply_device("PesoCorrente",false)
	level._on_exit(level.exit_marker)
	check(not level.completed and not level.exit_marker.activated,"Portal permanece bloqueado enquanto a carroça espera a cesta")
	await place(cargo.destination+Vector2(-130,0),4)
	await frames(2)
	check(cargo.placing and level.supply_placement_active and level.supply_departure_active,"A proximidade inicia automaticamente a animação de entrega")
	check(not level.pipo.controls_enabled and level.switch_button.disabled,"Controles são suspensos durante a colocação da cesta")
	check(art.pose=="delivery_place","Pipo assume a pose de colocar a cesta na carroça")
	check(not cargo.carried and not level.pipo.is_carrying(),"Cesta deixa as mãos de Pipo antes de seguir para a carroça")
	var placement_start := cargo.position
	await frames(28)
	check(cargo.placing and cargo.position.distance_to(cargo.destination)<placement_start.distance_to(cargo.destination),"Cesta percorre um arco progressivo até o compartimento")
	await frames(32)
	check(cargo.active and cargo.departing and not level.supply_placement_active,"Conclusão da colocação encaixa a cesta e inicia o burrinho")
	check(level.mechanisms.CargaRio.active,"Entrega automática integra o mecanismo necessário da fase")
	check(cargo._cart_frames.size()==4 and cargo.departure_offset==0.0,"Carroça prepara quatro poses antes de partir")
	check(cargo.CART_BASKET_HEIGHT==68.0 and cargo.CART_BASKET_CENTER==Vector2(-22,-34),"Cesta entregue mantém tamanho legível e fica encaixada no compartimento")
	check(cargo.has_method("_draw_cart_front_lip"),"Borda frontal mantém a cesta visualmente dentro da carroça")
	await frames(65)
	check(cargo.departure_offset>0 and cargo.cart_frame in range(4),"Burrinho caminha e leva a carroça em direção ao vilarejo")
	await frames(150)
	check(cargo.departed and not level.supply_departure_active and level.pipo.controls_enabled and not level.switch_button.disabled,"Controle retorna ao jogador depois que a carroça sai")
	check(not cargo.visible and not cargo.is_processing(),"Carroça deixa a fase e não reaparece adiante")
	check(not cargo.should_draw_waiting_basket(),"Cesta permanece fora da fase depois de seguir para o vilarejo")
	level._on_exit(level.exit_marker)
	check(level.completed,"Portal permite concluir a fase depois da entrega na carroça")
	await close_level()
	await open_stage(2,"2")
	check(not level.mechanisms.has("CargaMargem"),"2-2 não reutiliza a animação de carroça e cesta")
	await close_level()
	await open_stage(2,"3")
	check(level.mechanisms.has("CargaPonte"),"2-3 possui transporte de provisões")
	await close_level()
	print("RESULTADO TRANSPORTE DE OBJETOS: %d verificações, %d falhas" % [checks,failures])
	quit(1 if failures else 0)
