extends "res://tests/coop_test.gd"

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	level = load("res://scenes/levels/vertical_slice.tscn").instantiate()
	level.save_enabled = false
	root.add_child(level)
	await frames(30)
	var art: Node2D = level.squirrel.get_node("Illustration")
	await place(Vector2(780,760))
	key(KEY_D,true)
	await frames(25)
	check(art.pose=="push_attempt","Tico faz força contra a pedra ao segurar direção")
	var phases: Dictionary = {}
	for i in 60:
		await frames(1)
		phases[art.push_frame] = true
	check(phases.size()==4,"Esforço de Tico percorre quatro poses")
	check(absf(level.stone.position.x-850)<1,"Esforço visual não permite a Tico mover a pedra")
	level.set_paused(true)
	var previous_frame: int = art.push_frame
	await frames(20)
	check(art.push_frame==previous_frame,"Pausa congela o ciclo de esforço")
	level.set_paused(false)
	key(KEY_D,false)
	await frames(5)
	check(art.pose!="push_attempt","Soltar direção encerra o esforço")
	key(KEY_A,true)
	await frames(10)
	check(art.pose=="run","Afastar-se da pedra retoma corrida")
	key(KEY_A,false)
	await place(Vector2(780,600),1)
	key(KEY_D,true)
	await frames(3)
	check(art.pose!="push_attempt","Contato sem apoio no chão não inicia esforço")
	await place(Vector2(920,760))
	key(KEY_A,true)
	await frames(25)
	check(art.pose=="push_attempt" and level.tico.facing==-1,"Esforço também funciona virado à esquerda")
	await place(Vector2(770,760))
	check(level.switch_character(),"Pipo assume antes da pedra")
	art = level.pipo.get_node("Illustration")
	key(KEY_D,true)
	await frames(25)
	phases.clear()
	var start_x: float = level.stone.position.x
	for i in 100:
		await frames(1)
		if art.pose == "push": phases[art.push_frame] = true
	check(level.stone.position.x>start_x+80,"Pipo mantém o deslocamento normal da pedra")
	check(phases.size()==4,"Pipo alterna quatro passadas enquanto empurra")
	check(level.sounds.played.get("step",0)>0,"Empurrar acompanha os passos com áudio")
	await frames(200)
	check(art.pose=="push_attempt" and art.push_frame==0,"No limite da pedra, Pipo faz força sem andar parado")
	check(level.stone.position.x<=1190.1,"Animação preserva o limite físico da pedra")
	key(KEY_D,false)
	await frames(5)
	check(art.pose not in ["push","push_attempt"],"Pipo para de empurrar ao soltar direção")
	print("RESULTADO: %d verificações, %d falhas" % [checks,failures])
	release()
	level.queue_free()
	await frames(3)
	OS.delay_msec(100)
	quit(1 if failures else 0)
