extends "res://tests/prototype_test.gd"
const SLICE_SLOT := "user://stage7_test_only.json"

func open_level() -> void:
	level = load("res://scenes/levels/vertical_slice.tscn").instantiate()
	level.save_store.path = SLICE_SLOT
	root.add_child(level)
	await frames(35)

func run() -> void:
	root.size = Vector2i(1280,720)
	root.content_scale_size = Vector2i(1280,720)
	DirAccess.remove_absolute(SLICE_SLOT)
	await open_level()
	check(level._art_ready and level.background.texture != null,"Bosque carrega ilustrações e HUD")
	check(not level.squirrel.sprite.visible and level.squirrel.has_node("Illustration"),"Apresentação substitui sprite provisório sem mudar controlador")
	check(level.sounds.music.playing and level.sounds.music.stream.loop_mode==1,"Música inicia em loop")
	level.set_paused(true)
	check(level.pause_overlay.visible and level.sounds.music.stream_paused,"Pausa exibe menu e suspende música")
	level.toggle_music()
	level.toggle_effects()
	check(not level.music_enabled and not level.effects_enabled,"Opções controlam música e efeitos separadamente")
	level.set_paused(false)
	check(not level.pause_overlay.visible and not level.sounds.music.stream_paused,"Continuar remove menu e retoma relógio de áudio")
	await close_level()
	await open_level()
	check(not level.music_enabled and not level.effects_enabled,"Preferências persistem ao reabrir")
	level.toggle_music()
	level.toggle_effects()
	# Verificar eventos físicos reais em vez de forçar estados de animação.
	key(KEY_SPACE,true)
	await frames(8)
	check(level.tico.get_node("Illustration").pose=="jump","Salto usa pose ilustrada")
	await frames(40)
	check(level.tico.get_node("Illustration").pose=="glide","Planar usa pose com cauda aberta")
	key(KEY_SPACE,false)
	await frames(40)
	check(level.sounds.played.get("jump",0)>0 and level.sounds.played.get("land",0)>0,"Salto e pouso disparam áudio")
	level.tico.take_damage(Vector2(200,760))
	await frames(2)
	check(level.tico.get_node("Illustration").pose=="hurt","Dano usa pose própria")
	await frames(60)
	check(level.switch_character(),"Troca continua disponível com nova apresentação")
	await frames(20)
	key(KEY_E,true)
	await frames(2)
	check(level.tico.get_node("Illustration").pose=="prepare","Pipo antecipa investida visualmente")
	await frames(17)
	check(level.tico.get_node("Illustration").pose=="charge","Pipo usa pose de investida")
	key(KEY_E,false)
	await frames(60)
	for i in 40: level.puff(Vector2(160,760),Color.WHITE)
	check(get_nodes_in_group("slice_effects").size()<=16,"Efeitos respeitam limite de emissão")
	await frames(60)
	check(get_nodes_in_group("slice_effects").is_empty(),"Efeitos expiram e liberam nós")
	level.new_adventure()
	await frames(30)
	# Percurso real com arte, áudio, física e save simultâneos.
	await walk_to(320)
	key(KEY_SPACE,true)
	await walk_to(770)
	key(KEY_SPACE,false)
	await frames(90)
	level.switch_character()
	await walk_to(1120)
	await frames(20)
	check(level.gate_open,"Slice: pedra abre portão")
	level.switch_character()
	key(KEY_SPACE,true)
	await walk_to(1280)
	key(KEY_SPACE,false)
	await walk_to(2020)
	await frames(20)
	level.switch_character()
	await walk_to(2110)
	await frames(15)
	key(KEY_E,true)
	await frames(65)
	key(KEY_E,false)
	check(level.heavy.destroyed,"Slice: impacto rompe parede")
	await walk_to(2900)
	await frames(20)
	check(level.secret.taken,"Slice: faro e segredo continuam acessíveis")
	await walk_to(3070)
	await frames(40)
	check(level.checkpoint_active,"Slice: bandeira ativa retorno")
	level.switch_character()
	await walk_to(3200)
	for target in [3370,3510,3650]:
		key(KEY_SPACE,true)
		await walk_to(target,240)
		key(KEY_SPACE,false)
		await frames(65)
	check(level.completed and level.result_panel.visible,"Slice completo até resultado")
	check(level.tico.get_node("Illustration").pose=="celebrate","Conclusão mantém animação de celebração")
	check(level.sounds.played.get("victory",0)>0,"Conclusão toca fanfarra")
	await close_level()
	DirAccess.remove_absolute(SLICE_SLOT)
	print("RESULTADO: %d verificações, %d falhas" % [checks,failures])
	quit(1 if failures else 0)
