extends RefCounted
const VILLAGE = preload("res://assets/narrative/opening_village.png")
const OWL_TRAPPED = preload("res://assets/narrative/opening_owl_trapped.png")
const OWL_RESCUED = preload("res://assets/narrative/opening_owl_rescued.png")

static func steps() -> Array:
	return [
		{"type":"scene","title":"O vilarejo na floresta","background":VILLAGE,"actor_position":Vector2(0.14,0.67)},
		{"type":"dialogue","speaker":"Narrador","text":"O inverno estava chegando. Todos guardavam comida para os dias frios."},
		{"type":"camera","focus":Vector2(0.20,0.52),"zoom":1.08,"duration":0.85},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Ainda cabem muitas nozes no meu depósito! Vou buscar mais para o vilarejo."},
		{"type":"animation","actor":"tico","animation":"run_and_jump","duration":1.65,"from":Vector2(0.14,0.67),"to":Vector2(0.58,0.62),"arc":72.0,"pose":"run"},
		{"type":"camera","focus":Vector2(0.68,0.48),"zoom":1.11,"duration":0.9},
		{"type":"dialogue","speaker":"Narrador","text":"Tico correu, saltou e procurou por toda parte. Mas encontrou muito menos comida do que esperava."},
		{"type":"animation","actor":"tico","animation":"look_around","duration":1.15,"from":Vector2(0.58,0.62),"to":Vector2(0.60,0.62),"arc":3.0,"pose":"gesture"},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Estranho... até os depósitos estão quase vazios. Preciso procurar além das trilhas conhecidas."},
		{"type":"transition","duration":0.7,"color":"fff0c9"},
		{"type":"scene","title":"Além das trilhas conhecidas","background":OWL_TRAPPED,"actor_position":Vector2(0.17,0.67)},
		{"type":"camera","focus":Vector2(0.70,0.38),"zoom":1.09,"duration":0.9},
		{"type":"dialogue","speaker":"Narrador","text":"Entre penas caídas e galhos quebrados, Tico ouviu um pedido de ajuda."},
		{"type":"dialogue","speaker":"Valda","text":"Olá! Você poderia me ajudar? Estes galhos prenderam minha asa."},
		{"type":"camera","focus":Vector2(0.22,0.58),"zoom":1.12,"duration":0.75},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Claro! Fique tranquila. Vou tirar você daí."},
		{"type":"animation","actor":"tico","animation":"rescue_valda","duration":1.7,"from":Vector2(0.17,0.67),"to":Vector2(0.47,0.64),"arc":24.0,"pose":"run"},
		{"type":"transition","duration":0.55,"color":"fff0c9"},
		{"type":"scene","title":"Uma nova amiga","background":OWL_RESCUED,"actor_position":Vector2(0.34,0.67)},
		{"type":"event","id":"owl_rescued"},
		{"type":"camera","focus":Vector2(0.67,0.40),"zoom":1.10,"duration":0.85},
		{"type":"dialogue","speaker":"Valda","text":"Muito obrigada, pequeno explorador. Você interrompeu sua jornada para me ajudar."},
		{"type":"camera","focus":Vector2(0.34,0.58),"zoom":1.12,"duration":0.75},
		{"type":"animation","actor":"tico","animation":"introduce_tico","duration":0.8,"from":Vector2(0.34,0.67),"to":Vector2(0.35,0.67),"arc":2.0,"pose":"gesture"},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Eu sou Tico. Moro no vilarejo perto daqui."},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"O inverno está chegando, mas nossos depósitos estão quase vazios. Estou procurando comida para todos."},
		{"type":"camera","focus":Vector2(0.67,0.38),"zoom":1.13,"duration":0.8},
		{"type":"dialogue","speaker":"Valda","text":"Meu nome é Valda. Há muitos anos observo os caminhos desta floresta."},
		{"type":"dialogue","speaker":"Valda","text":"A comida também está desaparecendo em outras partes do bosque. Muitos animais precisarão de ajuda antes do inverno."},
		{"type":"camera","focus":Vector2(0.49,0.45),"zoom":1.04,"duration":0.9},
		{"type":"dialogue","speaker":"Valda","text":"Você demonstrou coragem e bondade, Tico. Acredito que pode descobrir o que está acontecendo e unir os animais."},
		{"type":"animation","actor":"tico","animation":"tico_reflects","duration":1.0,"from":Vector2(0.35,0.67),"to":Vector2(0.36,0.67),"arc":1.0,"pose":"gesture"},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Nunca fui tão longe... mas não posso deixar o bosque sem comida."},
		{"type":"dialogue","speaker":"Tico","portrait":"tico","text":"Eu aceito, Valda. Vou ajudar o vilarejo e todos os animais que encontrar!"},
		{"type":"event","id":"first_clue_received"},
		{"type":"camera","focus":Vector2(0.80,0.48),"zoom":1.07,"duration":1.0},
		{"type":"dialogue","speaker":"Valda","text":"Comece seguindo a trilha de nozes. Observe também as penas: elas indicarão caminhos importantes."},
		{"type":"dialogue","speaker":"Valda","text":"Siga em frente, Tico. A floresta conta com você."},
		{"type":"animation","actor":"tico","animation":"begin_journey","duration":1.65,"from":Vector2(0.36,0.67),"to":Vector2(0.78,0.62),"arc":34.0,"pose":"run"},
		{"type":"transition","duration":0.75,"color":"fff4d7"},
		{"type":"scene","title":"Tico e a Floresta das Nozes","background":VILLAGE,"actor_position":Vector2(0.50,0.66)},
		{"type":"camera","focus":Vector2(0.50,0.45),"zoom":1.05,"duration":0.9},
		{"type":"dialogue","speaker":"Uma aventura entre amigos","text":"Siga a trilha. Encontre comida. Ajude o bosque."}
	]
